fix stringNo/StringNumber bug in vimo[checkPathNo]. Add vimo unixmode

diff --git a/vimo b/vimo
--- a/vimo
+++ b/vimo
@@ -1,4 +1,4 @@
-!/bin/bash
+#!/bin/bash
 
 # Function 'usage' defined before set options. All other functions defined afterwards
 usage () {
@@ -141,7 +141,7 @@ AUTHOR
 END
 }
 
-# Set Options
+# ENV variables are VIMOMAX, VIMOCHOICE, VIMODIR, an  EDITOR
 
 if [[ -z "${VIMOMAX// }" ]];then
 	# If the EVV variable VIMOMAX is not set, set it
@@ -149,11 +149,12 @@ if [[ -z "${VIMOMAX// }" ]];then
 fi 
 
 if [[ -z "${VIMOCHOICE// }" ]];then
-	# If the EVV variable VIMOMAX is not set, set it
+	# If the ENV variable VIMOCHOICE is not set, set it
 	VIMOCHOICE=2 
 fi 
+# Set Options
 
-while getopts ":cdfhilvm" opt; do
+while getopts ":cdfhilvmx" opt; do
 	case $opt in
 		c)
 			usecurrentdir=1 
@@ -180,6 +181,9 @@ while getopts ":cdfhilvm" opt; do
 		v)
 			verbose=1 
 			;;
+		x)
+			unixmode=1 
+			;;
 	esac
 done
 shift $(( ${OPTIND} - 1 ))
@@ -193,11 +197,11 @@ checkArg () {
 	fi
 
 	if [[ ! ${1} ]]; then
-		echo "-->Missing argument ('vimo -h' for help)" 
+		echo "--> Missing argument ('vimo -h' for help)" 
 		exit 1
 	fi
 
-	if [[ ${#} -gt 1 &&  ${multisearch} -ne 1 ]]; then
+	if [[ ${#} -gt 1 && ${multisearch} -ne 1 ]]; then
 		openAll "${@}"
 		exit 1
 	fi
@@ -209,8 +213,7 @@ setEditor () {
 		showFunctionName
 	fi
 
-	# if EDITOR is not set, use vim 
-	if [[ -z "${EDITOR// }" ]];then
+	if [[ -z "${EDITOR// }" ]];then # if EDITOR is not set, use vim 
 		EDITOR='vim'
 	fi 
 }
@@ -270,8 +273,8 @@ findPaths () {
 stringNumber () {
 
 	declare -a arrOfStrings=(${@})
-	declare -i stringNo="${#arrOfStrings[@]}"
-	echo "${stringNo}"
+	declare -i string_no="${#arrOfStrings[@]}"
+	echo "${string_no}"
 }
 
 checkPathsNumber () {
@@ -282,9 +285,10 @@ checkPathsNumber () {
 	if [[ ${verbose} == 1 ]]; then
 		showFunctionName
 	fi
-	stringNo=$(stringNumber "${1}")
-	if [[ ${stringNumber} -gt ${VIMOMAX} ]];then
-		read -p  "${stringNo} files detected. Do you wish to continute [Y/n]?"\
+	string_no=$(stringNumber "${1}")
+	:
+	if [[ ${string_no} -gt ${VIMOMAX} ]];then
+		read -p  "${string_no} files detected. Do you wish to continute [Y/n]?"\
 			userchoice
 		if [[ $userchoice == [Yy]* ]]; then
 			echo "OK"
@@ -310,7 +314,10 @@ showFileDirPath () {
 		echo "Not found: ${@:2:$(($#-2))}" 
 	elif [[ ${@:${#@}} -eq 1 ]]; then 
 
-		if [[ ${fullpath} == 1 ]];then
+		if [[ ${unixmode} == 1 ]]; then
+			echo  "${find_paths}" 
+			exit 1
+		elif [[ ${fullpath} == 1 ]];then
 			find_paths=${find_paths#$HOME}
 		else
 			find_paths="${find_paths#${VIMODIR}}"
@@ -336,6 +343,14 @@ showFilesDirsPaths () {
 
 	if [[ len > 1 ]]; then
 
+		if [[ ${unixmode} == 1 ]];then
+
+			for ((i=0; i < len; i++)); do
+				echo "${arrpaths[i]}"
+			done 
+			exit 1
+		fi
+
 		if [[ ${fullpath} == 1 ]];then
 			arrpaths=(${arrpaths[@]#${HOME}})
 		else
@@ -359,12 +374,13 @@ openFile () {
 		showFunctionName
 	fi
 
-	stringNo=$(stringNumber "${1}") #could fix this
+	string_no=$(stringNumber "${1}") #could fix this
 
-	if [[ ${stringNo} -eq 0 ]];then
+	if [[ ${string_no} -eq 0 ]];then
+		shift
 		echo "File not detected --> ${1}"
 		exit 1
-	elif [[  ${stringNo} -eq 1 ]];then
+	elif [[  ${string_no} -eq 1 ]];then
 		$EDITOR  "${find_paths}"  
 		exit 0
 	fi
@@ -395,11 +411,11 @@ openAll () {
 
 	foundFiles=$(echo -e "${foundFiles}")
 	declare -a arrFoundFiles=(${foundFiles})
-  declare -i count="${#arrFoundFiles[@]}"
+	declare -i count="${#arrFoundFiles[@]}"
 
 	if [[ ${count} -gt ${VIMOCHOICE} ]];then
 		read -p  "--> ${count} files will be opened in ${EDITOR}. \
-Do you wish to continue [Y/n]?" userchoice
+			Do you wish to continue [Y/n]?" userchoice
 		if [[ $userchoice == [Yy]* ]]; then
 			$EDITOR ${foundFiles}
 		else
@@ -410,7 +426,7 @@ Do you wish to continue [Y/n]?" userchoice
 
 		$EDITOR ${foundFiles}
 	else 
-		echo "-->Files not found in current directory: ${@}"
+		echo "--> Files not found in current directory: ${@}"
 		echo "--> To search for multiple terms, use the '-m' option"
 	fi 
 }
@@ -423,7 +439,7 @@ showSelectList () {
 		showFunctionName
 	fi
 
-	stringNo=$(stringNumber "${1}")
+	string_no=$(stringNumber "${1}")
 	pathlist="${1}"
 	IFS=$'\n'  # necessary if find_paths contains spaces in returned filepaths 
 	arrpath=($pathlist)
@@ -486,8 +502,8 @@ init () {
 
 		findPaths  "${@}" 1 
 		checkPathsNumber "${find_paths}"
-		showFileDirPath "${find_paths}" "${@}" "${stringNo}"
-		pipeToLess showFilesDirsPaths  "${stringNo}"
+		showFileDirPath "${find_paths}" "${@}" "${string_no}"
+		pipeToLess showFilesDirsPaths  "${string_no}"
 		exit 1
 	else
 		# Search for files only 
@@ -495,12 +511,12 @@ init () {
 		if [[ ${listonly} == 1 ]];then
 			findPaths  "${@}" 0 
 			checkPathsNumber "${find_paths}"
-			showFileDirPath "${find_paths}" "${@}" "${stringNo}"
-			pipeToLess showFilesDirsPaths  "${stringNo}"
+			showFileDirPath "${find_paths}" "${@}" "${string_no}"
+			pipeToLess showFilesDirsPaths  "${string_no}"
 		else  
 			findPaths  "${@}" 0 
 			checkPathsNumber "${find_paths}"
-			openFile "${find_paths}"
+			openFile "${find_paths}" "$@"
 			showSelectList "${find_paths}"
 		fi 
 	fi
